GAMES = [
    {
        "appid": 3513350,
        "name": "Wuthering Waves",
        "category": "Open-world Action RPG",
        "status": "active",
    },
    {
        "appid": 4162040,
        "name": "Zenless Zone Zero",
        "category": "Action RPG",
        "status": "active",
    },
    {
        "appid": 1671200,
        "name": "Honkai Impact 3rd",
        "category": "Action RPG",
        "status": "active",
    },
    {
        "appid": 4125930,
        "name": "Punishing: Gray Raven",
        "category": "Action RPG",
        "status": "active",
    },
    {
        "appid": 3557620,
        "name": "Blue Archive",
        "category": "Tactical RPG",
        "status": "active",
    },
    {
        "appid": 3347400,
        "name": "GIRLS' FRONTLINE 2: EXILIUM",
        "category": "Tactical RPG",
        "status": "active",
    },
    {
        "appid": 1973530,
        "name": "Limbus Company",
        "category": "Turn-based RPG",
        "status": "active",
    },
    {
        "appid": 3224770,
        "name": "Umamusume: Pretty Derby",
        "category": "Character Collection / Racing",
        "status": "active",
    },
    {
        "appid": 2668080,
        "name": "Snowbreak: Containment Zone",
        "category": "Shooter / RPG",
        "status": "active",
    },
    {
        "appid": 3092660,
        "name": "Reverse: 1999",
        "category": "Turn-based RPG",
        "status": "active",
    },
    {
        "appid": 4195600,
        "name": "AFK Journey",
        "category": "Idle / RPG",
        "status": "active",
    },
    {
        "appid": 2064650,
        "name": "Tower of Fantasy",
        "category": "Open-world RPG",
        "status": "active",
    },
    {
        "appid": 2526380,
        "name": "Sword of Convallaria",
        "category": "Tactical RPG",
        "status": "active",
    },
    {
        "appid": 4508340,
        "name": "NTE: Neverness to Everness",
        "category": "Open-world Action RPG",
        "status": "active",
    },
    {
        "appid": 4247320,
        "name": "OUTERPLANE",
        "category": "Turn-based RPG",
        "status": "active",
    },
    {
        "appid": 2167580,
        "name": "Summoners War: Chronicles",
        "category": "MMORPG / Character Collection",
        "status": "active",
    },
    {
        "appid": 3813590,
        "name": "Summoners War: RUSH",
        "category": "RPG / Auto-battler",
        "status": "active",
    },
    {
        "appid": 4732690,
        "name": "Arknights: Endfield",
        "category": "RPG / Strategy",
        "status": "upcoming",
    },
]